// Generated by scripts/wire-route.mjs and updated by /extract_components.
// Mirrors https://www.bloomroomsocial.com/menu  →  /menu
import { PageReveal } from '@/components/PageReveal'
import { PageInteractive } from '@/components/PageInteractive'
import { Header } from '@/components/shared/Header'
import { Footer } from '@/components/shared/Footer'
import { STWrapper } from '@/components/shared/STWrapper'
import { Menu } from '@/components/generated/Menu'
import '@/components/generated/menu.css'
import '@/components/generated/menu.animations.css'

export default function Route() {
  return (
    <PageReveal>
      <PageInteractive />
      <Header />
      <Menu />
      <Footer />
      <STWrapper />
    </PageReveal>
  )
}
