// Generated by scripts/wire-route.mjs and updated by /extract_components.
// Mirrors https://www.bloomroomsocial.com/menu  →  /menu
import { PageRenderer } from '@/components/generated/PageRenderer'
import { PageReveal } from '@/components/PageReveal'
import { PageInteractive } from '@/components/PageInteractive'
import { Header } from '@/components/shared/Header'
import { Footer } from '@/components/shared/Footer'
import { STWrapper } from '@/components/shared/STWrapper'
import tree from '@/components/generated/menu.tree.json'
import animMap from '@/components/generated/menu.animations.json'
import linkMap from '@/components/routes.manifest.json'
import '@/components/generated/menu.css'
import '@/components/generated/menu.animations.css'

const SHARED_SKIP = ['navbar w-nav', 'footer-divisor', 'st_wrapper']

export default function Page() {
  return (
    <PageReveal>
      <PageInteractive />
      <Header />
      <PageRenderer tree={tree} animMap={animMap as Record<string, string>} linkMap={linkMap} skip={SHARED_SKIP} />
      <Footer />
      <STWrapper />
    </PageReveal>
  )
}
