// Generated by scripts/wire-route.mjs and updated by /extract_components.
// Mirrors https://www.bloomroomsocial.com/  →  /
import { PageReveal } from '@/components/PageReveal'
import { PageInteractive } from '@/components/PageInteractive'
import { Header } from '@/components/shared/Header'
import { Footer } from '@/components/shared/Footer'
import { STWrapper } from '@/components/shared/STWrapper'
import { Page } from '@/components/generated/Page'
import '@/components/generated/page.css'
import '@/components/generated/page.animations.css'

export default function Route() {
  return (
    <PageReveal>
      <PageInteractive />
      <Header />
      <Page />
      <Footer />
      <STWrapper />
    </PageReveal>
  )
}
