#!/usr/bin/env node
// Wires a captured page into the Next.js app router by writing
// `src/app/<path>/page.tsx` that imports the matching generated assets.
//
// Usage:
//   node scripts/wire-route.mjs <url> [--name=<slug>] [--path=<override>] [--force]
//
// The route path mirrors the source URL's pathname:
//   https://www.bloomroomsocial.com/menu  →  src/app/menu/page.tsx       (/menu)
//   https://www.bloomroomsocial.com/      →  src/app/page.tsx            (/)
//   https://www.bloomroomsocial.com/about/team → src/app/about/team/page.tsx
//
// Default --name is derived from the last URL path segment (or "page" for /).
// The script will refuse to overwrite an existing route file unless --force.
//
// Required generated artifacts (built by `npm run build:page-css --name=<slug>`
// and `npm run build:ix2 --name=<slug>`):
//   src/components/generated/<slug>.css
//   src/components/generated/<slug>.tree.json
//   src/components/generated/<slug>.animations.css
//   src/components/generated/<slug>.animations.json

import { mkdir, writeFile, access } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const APP_DIR = resolve(ROOT, 'src/app')
const GEN_DIR = resolve(ROOT, 'src/components/generated')

const log = (msg) => console.log(`[wire:route] ${msg}`)
const die = (msg) => { console.error(`[wire:route] ✗ ${msg}`); process.exit(1) }

const args = process.argv.slice(2)
if (args.length < 1) {
  die('Usage: node scripts/wire-route.mjs <url> [--name=<slug>] [--path=<override>] [--force]')
}

const [urlArg, ...rest] = args
let nameSlug = null
let pathOverride = null
let force = false
for (const a of rest) {
  if (a.startsWith('--name=')) nameSlug = a.split('=')[1]
  else if (a.startsWith('--path=')) pathOverride = a.split('=')[1]
  else if (a === '--force') force = true
  else die(`Unknown flag: ${a}`)
}

// Parse the URL. Allow either a full URL or a bare path ("/menu").
let pathname
if (urlArg.startsWith('/')) {
  pathname = urlArg
} else {
  try {
    pathname = new URL(urlArg).pathname
  } catch {
    die(`Invalid URL or path: ${urlArg}`)
  }
}
if (pathOverride) pathname = pathOverride.startsWith('/') ? pathOverride : `/${pathOverride}`

// Strip leading/trailing slashes, split into segments. "/" becomes [].
const segments = pathname.replace(/^\/+|\/+$/g, '').split('/').filter(Boolean)

// Default --name: last URL segment, or "page" for the root.
if (!nameSlug) nameSlug = segments[segments.length - 1] || 'page'

// Validate slug (filesystem-safe, also a valid JS identifier piece).
if (!/^[a-zA-Z0-9_-]+$/.test(nameSlug)) {
  die(`--name=${nameSlug} contains characters that won't import cleanly. Use letters, digits, _ or -.`)
}

// Verify the generated assets exist — otherwise the route would fail to compile.
const requiredFiles = [
  `${nameSlug}.css`,
  `${nameSlug}.tree.json`,
  `${nameSlug}.animations.css`,
  `${nameSlug}.animations.json`,
]
const missing = []
for (const f of requiredFiles) {
  try {
    await access(resolve(GEN_DIR, f))
  } catch {
    missing.push(f)
  }
}
if (missing.length) {
  die(`Missing generated files for --name=${nameSlug}:\n  ${missing.join('\n  ')}\n` +
      `Run:\n  npm run extract:page -- ${urlArg} --name=${nameSlug} [--viewport=…]\n` +
      `  npm run extract:ix2  -- ${urlArg} --name=${nameSlug}\n` +
      `  npm run build:page-css -- --name=${nameSlug}\n` +
      `  npm run build:ix2 -- --name=${nameSlug}`)
}

// Compute the route file path. App-router page files always live at
// `<route>/page.tsx`. Root path `/` collapses to `src/app/page.tsx`.
const routeDir = resolve(APP_DIR, ...segments)
const routeFile = resolve(routeDir, 'page.tsx')

try {
  await access(routeFile)
  if (!force) {
    die(`Route file already exists: ${routeFile}\nPass --force to overwrite.`)
  }
  log(`Overwriting ${routeFile} (--force)`)
} catch {
  // Doesn't exist — fine, we'll create it.
}

await mkdir(routeDir, { recursive: true })

const routePath = '/' + segments.join('/')
const contents = `// Generated by scripts/wire-route.mjs. Do not edit by hand.
// Mirrors ${urlArg}  →  ${routePath || '/'}
import { PageRenderer } from '@/components/generated/PageRenderer'
import { PageReveal } from '@/components/PageReveal'
import { PageInteractive } from '@/components/PageInteractive'
import tree from '@/components/generated/${nameSlug}.tree.json'
import animMap from '@/components/generated/${nameSlug}.animations.json'
import linkMap from '@/components/routes.manifest.json'
import '@/components/generated/${nameSlug}.css'
import '@/components/generated/${nameSlug}.animations.css'

export default function Page() {
  return (
    <PageReveal>
      <PageInteractive />
      <PageRenderer tree={tree} animMap={animMap as Record<string, string>} linkMap={linkMap} />
    </PageReveal>
  )
}
`

await writeFile(routeFile, contents)
log(`✓ Wrote ${routeFile}`)
log(`  Route   : ${routePath || '/'}`)
log(`  Imports : ${nameSlug}.css, ${nameSlug}.tree.json, ${nameSlug}.animations.{css,json}`)
log('Done. Restart `npm run dev` if it was already running.')
